import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.tsa.vector_ar.var_model import VAR
from statsmodels.tsa.statespace.varmax import VARMAX

ms = pd.read_excel('MASS SHOOTINGS.xlsx')

#cleaning
#Eliminando columnas que no necesito
ms.drop(['age','SCHOOL','GANG','CRIME','ALTERCATION','POLITICAL','FAMILY','RANDOM','WORK','latino','native am','asian','black','white','Na','NaN','NAA','NAAA','male','female','0G','1G','2G','3G','4G','5G','7G','8G','9G','10G','police intervention','civilian intervention','Latitude','Longitude'], axis=1, inplace=True)

#Cambiando el nombre de las variables
ms.rename(columns = {'S#':'Caso_No.'}, inplace= True)
ms.rename(columns = {'Title':'Titulo'}, inplace= True)
ms.rename(columns = {'Location':'Lugar'}, inplace= True)
ms.rename(columns = {'Date':'Dia'}, inplace= True)
ms.rename(columns = {'civilian intervention':'Intervencion_civil'}, inplace= True)
ms.rename(columns = {'police intervention':'Intervencion_policial'}, inplace= True)
ms.rename(columns = {'suicide':'Suicidio'}, inplace= True)
ms.rename(columns = {'age.1':'Edad'}, inplace= True)
ms.rename(columns = {'motive':'Motivo'}, inplace= True)
ms.rename(columns = {'Summary':'Resumen'}, inplace= True)
ms.rename(columns = {'Fatalities':'Muertes'}, inplace= True)
ms.rename(columns = {'Injured':'Heridos'}, inplace= True)
ms.rename(columns = {'Total victims':'Victimas_Totales'}, inplace= True)
ms.rename(columns = {'Mental Health Issues':'Problemas_de_Salud_Mental'}, inplace= True)
ms.rename(columns = {'Race':'Raza'}, inplace= True)
ms.rename(columns = {'Gender':'Genero'}, inplace= True)
ms.rename(columns = {'Latitude':'Latitud'}, inplace= True)
ms.rename(columns = {'Longitude':'Longitud'}, inplace= True)
ms.rename(columns = {'STATE':'Estado'}, inplace= True)
ms.rename(columns = {'GUNCONTROL':'Control_de_armas'}, inplace= True)
ms.rename(columns = {'STRICT':'Estrictos'}, inplace= True)
ms.rename(columns = {'NOT STRICT':'No_Estrictos'}, inplace= True)
ms.rename(columns = {'WELL':'Sanos'}, inplace= True)
ms.rename(columns = {'ILL':'Enfermos'}, inplace= True)

#Mudando los datos a una nueva base de datos
ms.to_excel('MS_NEW.xlsx', sheet_name='Base de Datos')
msn = pd.read_excel("MS_NEW.xlsx")

print("La proporción de agresores sin problemas de salud mental es de:", msn['Sanos'].mean())
print("La proporción de agresores con problemas de salud mental es de:", msn['Enfermos'].mean())

g = msn.groupby('Problemas_de_Salud_Mental')
UC = g.get_group('Unclear')
UK = g.get_group('Unknown')
print("La proporción de agresores con situación de salud mental no clara es de:", len(UC)/len(msn))
print("La proporción de agresores con situación de salud mental desconocida es de:", len(UK)/len(msn))
e = msn.groupby('Estado')

#Para nuestro objetivo vamos a calcular el total de víctimas que hay en cada estado, el promedio general y por estado.
AK = e.get_group('AK')
AL = e.get_group('AL')
AR = e.get_group('AR')
AZ = e.get_group('AZ')
CA = e.get_group('CA')
CO = e.get_group('CO')
CT = e.get_group('CT')
DC = e.get_group('DC')
DE = e.get_group('DE')
FL = e.get_group('FL')
GA = e.get_group('GA')
HI = e.get_group('HI')
IA = e.get_group('IA')
ID = e.get_group('ID')
IL = e.get_group('IL')
IN = e.get_group('IN')
KS = e.get_group('KS')
KY = e.get_group('KY')
LA = e.get_group('LA')
MA = e.get_group('MA')
MD = e.get_group('MD')
ME = e.get_group('ME')
MI = e.get_group('MI')
MN = e.get_group('MN')
MO = e.get_group('MO')
MS = e.get_group('MS')
MT = e.get_group('MT')
NC = e.get_group('NC')
NE = e.get_group('NE')
NJ = e.get_group('NJ')
NM = e.get_group('NM')
NV = e.get_group('NV')
NY = e.get_group('NY')
OH = e.get_group('OH')
OK = e.get_group('OK')
OR = e.get_group('OR')
PA = e.get_group('PA')
SC = e.get_group('SC')
SD = e.get_group('SD')
TN = e.get_group('TN')
TX = e.get_group('TX')
UT = e.get_group('UT')
VA = e.get_group('VA')
VT = e.get_group('VT')
WA = e.get_group('WA')
WI = e.get_group('WI')
WV = e.get_group('WV')
WY = e.get_group('WY')

SAK=AK['Victimas_Totales'].sum()
SAL=AL['Victimas_Totales'].sum()
SAR=AR['Victimas_Totales'].sum()
SAZ=AZ['Victimas_Totales'].sum()
SCA=CA['Victimas_Totales'].sum()
SCO=CO['Victimas_Totales'].sum()
SCT=CT['Victimas_Totales'].sum()
SDC=DC['Victimas_Totales'].sum()
SDE=DE['Victimas_Totales'].sum()
SFL=FL['Victimas_Totales'].sum()
SGA=GA['Victimas_Totales'].sum()
SHI=HI['Victimas_Totales'].sum()
SIA=IA['Victimas_Totales'].sum()
SID=ID['Victimas_Totales'].sum()
SIL=IL['Victimas_Totales'].sum()
SIN=IN['Victimas_Totales'].sum()
SKS=KS['Victimas_Totales'].sum()
SKY=KY['Victimas_Totales'].sum()
SLA=LA['Victimas_Totales'].sum()
SMA=MA['Victimas_Totales'].sum()
SMD=MD['Victimas_Totales'].sum()
SME=ME['Victimas_Totales'].sum()
SMI=MI['Victimas_Totales'].sum()
SMN=MN['Victimas_Totales'].sum()
SMO=MO['Victimas_Totales'].sum()
SMS=MS['Victimas_Totales'].sum()
SMT=MT['Victimas_Totales'].sum()
SNC=NC['Victimas_Totales'].sum()
SNE=NE['Victimas_Totales'].sum()
SNJ=NJ['Victimas_Totales'].sum()
SNM=NM['Victimas_Totales'].sum()
SNV=NV['Victimas_Totales'].sum()
SNY=NY['Victimas_Totales'].sum()
SOH=OH['Victimas_Totales'].sum()
SOK=OK['Victimas_Totales'].sum()
SOR=OR['Victimas_Totales'].sum()
SPA=PA['Victimas_Totales'].sum()
SSC=SC['Victimas_Totales'].sum()
SSD=SD['Victimas_Totales'].sum()
STN=TN['Victimas_Totales'].sum()
STX=TX['Victimas_Totales'].sum()
SUT=UT['Victimas_Totales'].sum()
SVA=VA['Victimas_Totales'].sum()
SVT=VT['Victimas_Totales'].sum()
SWA=WA['Victimas_Totales'].sum()
SWI=WI['Victimas_Totales'].sum()
SWV=WV['Victimas_Totales'].sum()
SWY=WY['Victimas_Totales'].sum()

print("El total de víctimas en AK es de:",SAK)
print("El total de víctimas en AL es de:",SAL)
print("El total de víctimas en AR es de:",SAR)
print("El total de víctimas en AZ es de:",SAZ)
print("El total de víctimas en CA es de:",SCA)
print("El total de víctimas en CO es de:",SCO)
print("El total de víctimas en CT es de:",SCT)
print("El total de víctimas en DC es de:",SDC)
print("El total de víctimas en DE es de:",SDE)
print("El total de víctimas en FL es de:",SFL)
print("El total de víctimas en GA es de:",SGA)
print("El total de víctimas en HI es de:",SHI)
print("El total de víctimas en IA es de:",SIA)
print("El total de víctimas en ID es de:",SID)
print("El total de víctimas en IL es de:",SIL)
print("El total de víctimas en IN es de:",SIN)
print("El total de víctimas en KS es de:",SKS)
print("El total de víctimas en KY es de:",SKY)
print("El total de víctimas en LA es de:",SLA)
print("El total de víctimas en MA es de:",SMA)
print("El total de víctimas en MD es de:",SMD)
print("El total de víctimas en ME es de:",SME)
print("El total de víctimas en MI es de:",SMI)
print("El total de víctimas en MN es de:",SMN)
print("El total de víctimas en MO es de:",SMO)
print("El total de víctimas en MS es de:",SMS)
print("El total de víctimas en MT es de:",SMT)
print("El total de víctimas en NC es de:",SNC)
print("El total de víctimas en NE es de:",SNE)
print("El total de víctimas en NJ es de:",SNJ)
print("El total de víctimas en NM es de:",SNM)
print("El total de víctimas en NV es de:",SNV)
print("El total de víctimas en NY es de:",SNY)
print("El total de víctimas en OH es de:",SOH)
print("El total de víctimas en OK es de:",SOK)
print("El total de víctimas en OR es de:",SOR)
print("El total de víctimas en PA es de:",SPA)
print("El total de víctimas en SC es de:",SSC)
print("El total de víctimas en SD es de:",SSD)
print("El total de víctimas en TN es de:",STN)
print("El total de víctimas en TX es de:",STX)
print("El total de víctimas en UT es de:",SUT)
print("El total de víctimas en VA es de:",SVA)
print("El total de víctimas en VT es de:",SVT)
print("El total de víctimas en WA es de:",SWA)
print("El total de víctimas en WI es de:",SWI)
print("El total de víctimas en WV es de:",SWV)
print("El total de víctimas en WY es de:",SWY)

print("El promedio de víctimas en AK es de:",AK['Victimas_Totales'].mean())
print("El promedio de víctimas en AL es de:",AL['Victimas_Totales'].mean())
print("El promedio de víctimas en AR es de:",AR['Victimas_Totales'].mean())
print("El promedio de víctimas en AZ es de:",AZ['Victimas_Totales'].mean())
print("El promedio de víctimas en CA es de:",CA['Victimas_Totales'].mean())
print("El promedio de víctimas en CO es de:",CO['Victimas_Totales'].mean())
print("El promedio de víctimas en CT es de:",CT['Victimas_Totales'].mean())
print("El promedio de víctimas en DC es de:",DC['Victimas_Totales'].mean())
print("El promedio de víctimas en DE es de:",DE['Victimas_Totales'].mean())
print("El promedio de víctimas en FL es de:",FL['Victimas_Totales'].mean())
print("El promedio de víctimas en GA es de:",GA['Victimas_Totales'].mean())
print("El promedio de víctimas en HI es de:",HI['Victimas_Totales'].mean())
print("El promedio de víctimas en IA es de:",IA['Victimas_Totales'].mean())
print("El promedio de víctimas en ID es de:",ID['Victimas_Totales'].mean())
print("El promedio de víctimas en IL es de:",IL['Victimas_Totales'].mean())
print("El promedio de víctimas en IN es de:",IN['Victimas_Totales'].mean())
print("El promedio de víctimas en KS es de:",KS['Victimas_Totales'].mean())
print("El promedio de víctimas en KY es de:",KY['Victimas_Totales'].mean())
print("El promedio de víctimas en LA es de:",LA['Victimas_Totales'].mean())
print("El promedio de víctimas en MA es de:",MA['Victimas_Totales'].mean())
print("El promedio de víctimas en MD es de:",MD['Victimas_Totales'].mean())
print("El promedio de víctimas en ME es de:",ME['Victimas_Totales'].mean())
print("El promedio de víctimas en MI es de:",MI['Victimas_Totales'].mean())
print("El promedio de víctimas en MN es de:",MN['Victimas_Totales'].mean())
print("El promedio de víctimas en MO es de:",MO['Victimas_Totales'].mean())
print("El promedio de víctimas en MS es de:",MS['Victimas_Totales'].mean())
print("El promedio de víctimas en MT es de:",MT['Victimas_Totales'].mean())
print("El promedio de víctimas en NC es de:",NC['Victimas_Totales'].mean())
print("El promedio de víctimas en NE es de:",NE['Victimas_Totales'].mean())
print("El promedio de víctimas en NJ es de:",NJ['Victimas_Totales'].mean())
print("El promedio de víctimas en NM es de:",NM['Victimas_Totales'].mean())
print("El promedio de víctimas en NV es de:",NV['Victimas_Totales'].mean())
print("El promedio de víctimas en NY es de:",NY['Victimas_Totales'].mean())
print("El promedio de víctimas en OH es de:",OH['Victimas_Totales'].mean())
print("El promedio de víctimas en OK es de:",OK['Victimas_Totales'].mean())
print("El promedio de víctimas en OR es de:",OR['Victimas_Totales'].mean())
print("El promedio de víctimas en PA es de:",PA['Victimas_Totales'].mean())
print("El promedio de víctimas en SC es de:",SC['Victimas_Totales'].mean())
print("El promedio de víctimas en SD es de:",SD['Victimas_Totales'].mean())
print("El promedio de víctimas en TN es de:",TN['Victimas_Totales'].mean())
print("El promedio de víctimas en TX es de:",TX['Victimas_Totales'].mean())
print("El promedio de víctimas en UT es de:",UT['Victimas_Totales'].mean())
print("El promedio de víctimas en VA es de:",VA['Victimas_Totales'].mean())
print("El promedio de víctimas en VT es de:",VT['Victimas_Totales'].mean())
print("El promedio de víctimas en WA es de:",WA['Victimas_Totales'].mean())
print("El promedio de víctimas en WI es de:",WI['Victimas_Totales'].mean())
print("El promedio de víctimas en WV es de:",WV['Victimas_Totales'].mean())
print("El promedio de víctimas en WY es de:",WY['Victimas_Totales'].mean())

print("La suma de la columna de las Victimas Totales es::", ms['Victimas_Totales'].sum())
print("La suma de la columna de los Suicidios es:", ms['Suicidio'].sum())
print("La media de la columna de las Victimas Totales es:", ms['Victimas_Totales'].mean())
print("La media de la columna de los Suicidios es:", ms['Suicidio'].mean())
print("La suma acumulada de la columna de las Victimas Totales es:", ms['Victimas_Totales'].cumsum())
print("La suma acumulada de la columna de los Suicidios es:", ms['Suicidio'].cumsum())
print("El resumen estadístico de la columna de las Victimas Totales es:", ms['Victimas_Totales'].describe())
print("El resumen estadístico de la columna de los Suicidios es:", ms['Suicidio'].describe())
print("La mediana de la columna de las Victimas Totales es:", ms['Victimas_Totales'].median())
print("La mediana de la columna de los Suicidios es:", ms['Suicidio'].median())
print("La varianza de la columna de las Victimas Totales es:", ms['Victimas_Totales'].var())
print("La varianza de la columna de los Suicidios es:", ms['Suicidio'].var())
print("La desviación estándar de la columna de las Victimas Totales es:", ms['Victimas_Totales'].std())
print("La desviación estándar de la columna de los Suicidios es:", ms['Suicidio'].std())

print("El promedio de víctimas totales en Estados Unidos es de:", ms['Victimas_Totales'].mean())

ms.corr()

Y = ms[ms['Problemas_de_Salud_Mental']=='Yes']
Y.to_csv('SI_TIENEN.csv', index=False)

UK = ms[ms['Problemas_de_Salud_Mental']=='Unknown']
UK.to_csv('Unknown.csv', index=False)

N = ms[ms['Problemas_de_Salud_Mental']=='No']
N.to_csv('NO_TIENEN.csv', index=False)

UC = ms[ms['Problemas_de_Salud_Mental']=='Unclear']
UC.to_csv('Unclear.csv', index=False)

ms['Muertes'].value_counts().sort_index().plot.bar()
ms[ms['Victimas_Totales'] < 35]['Victimas_Totales'].plot.hist()
ms.plot.area()
plt.show()

psm=[msn['Sanos'].mean(),msn['Enfermos'].mean(),len(UC)/len(msn),len(UK)/len(msn)]
nombres=["No","Si","No claro","Desconocido"]
plt.pie(psm,labels=nombres,autopct="%0.1f %%")
plt.title("Problemas de Salud Mental")
plt.show()

sns.countplot(msn['Problemas_de_Salud_Mental'])
plt.title("Problemas de Salud Mental")
plt.show()

sns.countplot(ms['Victimas_Totales'].head(60))
plt.show()

sns.countplot(ms['Suicidio'].head(60))
plt.show()

sns.relplot(x="Victimas_Totales", y="Estrictos", hue="Estado", alpha=0.5, palette="bright",height=3, data=msn, size=5)
plt.title('Estrictos vs Víctimas Totales',size=10)
plt.show()

#Forecasting
#model = VAR(np.column_stack((Heridos[:'2019-12-29'], deseasonalized_killed[:'2019-12-29'])))
#model_fit = model.fit(1)
#yhat = model_fit.forecast(model_fit.y, steps=13)
#injured_hat = np.array([yh[0] for yh in yhat])
#killed_hat = np.array([yh[1] for yh in yhat])
#victims_hat = (injured_reconstruct_df['2020-01-05':'2020-03-29']['seas']*injured_hat) + \
#               (killed_reconstruct_df['2020-01-05':'2020-03-29']['seas']+killed_hat)

#print('Total Victims Predict: \n', victims_hat)